### PR TITLE
Outdated 6.5 Service Pack number

### PR DESCRIPTION
**Pull request by wimsymons**
The target page shows Service Pack 13, this one still states Service Pack 11.

### CODE REVIEW

**Comment by aheim0** [comment]
Thanks for highlighting this - we will review.

**Comment by aheim0** [comment]
Tracked with CQDOC-19544

**Comment by wimsymons** [comment]
We're at Service Pack 14 now ...

**Comment by guillaumecarlino** [comment]
To avoid updating it each time, I just replaced the number by "latest". Also the 3 links were pointing to the same page so I reorganized the 6.5 section entirely. I also removed 6.2 and 6.3. Will be live shortly.

**Pull request closed without merging**
